module.exports=
{
    verifyAdmin:(req,res,next)=>
    {
        if(req.session.loggedInad)
        {
            next()
        }
        else
        {
            res.redirect('/admin')
        }

    },
    verifyUser:(req,res,next)=>
    {
        if(req.session.loggedIn)
        {
            next()
        }
        else{
            res.redirect('/')
        }
    }
}